// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const supabaseNotConfiguredError = "Supabase is not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.";

const createFallbackClient = () => {
  const createQueryStub = () => {
    return {
      select: () => queryStub,
      eq: () => queryStub,
      limit: () => queryStub,
      single: async () => ({ data: null, error: { message: supabaseNotConfiguredError } }),
      upsert: () => queryStub,
      insert: () => queryStub,
      delete: () => queryStub,
    } as const;
  };

  const queryStub = createQueryStub();

  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null } }),
      signInWithPassword: async () => ({ error: { message: supabaseNotConfiguredError } }),
      signUp: async () => ({ error: { message: supabaseNotConfiguredError } }),
      signOut: async () => ({ error: null }),
    },
    from: () => queryStub,
  } as unknown as typeof import("@supabase/supabase-js").SupabaseClient<Database>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase =
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : createFallbackClient();

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(supabaseNotConfiguredError);
}
